project:
  type: website

website:
  title: "Lev Kolinski"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: Research.qmd
      - text: "Data Science"
        href: data_projects.qmd

about:
  template: trestles
  image: media/headshot.jpeg
  image-shape: round
  image-width: 17em
  links:
    - text: LinkedIn
      href: https://linkedin.com/in/lev-kolinski
    - text: GitHub
      href: https://github.com/levkolinski
    - text: Google Scholar
      href: https://scholar.google.com/citations?user=kYy9ANAAAAAJ&hl=en&oi=ao
    - text: Email
      href: mailto:lev.kolinski@duke.edu

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: scripts.html

editor: visual

